# جلسه شانزدهم (مدیریت خطا)

از ابتدای درس، بارها و بارها به خطاهای مختلف در برنامه نوشتن برخورد کردیم و خطا برایمان به این معنی بود که برنامه اشکالی دارد و لذا برنامه متوقف شده و پیغام خطایی نمایش داده می‌شد. در این جلسه می‌خواهیم ببینیم که چگونه می‌شود خطاها را مدیریت کرد تا اجرای برنامه قطع نشود. چاپ پیغام خطای موردنظر خودمان، شناخت خطاهای مختلف و مواجهه با انواع خطا و ایجاد خطای خاصی که به نظر ما باید در برنامه ایجاد شود، از مهم‌ترین مواردی است که در این جلسه به آن می‌پردازیم.

## انواع خطا
- **خطای عدم رعایت تورفتگی (IndentationError)**

همان‌طور که در طول درس ملاحظه کردید، زبان پایتون به دروتورفتگی کد حساس است و عدم رعایت این مسأله باعث بروز خطای Indentation خواهد شد که به صورت زیر است:
```
File "~\test.py", line 2
    print(1)
IndentationError: unexpected indent
```
- **خطای مقدار (ValueError)**

این خطا هنگامی رخ می‌دهد که بخواهیم یک نوع داده را در جای نامناسب استفاده کنیم. مثلاً یک رشته غیرعددی را به عدد تبدیل کنیم. مثلاً اگر در برنامه خود بخواهیم رشته‌ی `salam` را به `int` تبدیل کنیم، پیغام خطای زیر نمایش داده می‌شود.
```
ValueError: invalid literal for int() with base 10: 'salam'
```
- **خطای نوع (TypeError)**

این خطا زمانی رخ می‌دهد که عملیات یا تابعی را روی نوع داده‌ی نامناسبی به کار بریم. برای مثال اگر سعی کنیم یک عدد و یک رشته را با هم جمع کنیم، پیغام خطای زیر چاپ می‌شود:
```
TypeError: unsupported operand type(s) for +: 'int' and 'str'
```
- **خطای تقسیم بر صفر (ZeroDivisionError)**

می‌دانیم که در ریاضی، تقسیم بر صفر تعریف نشده و به همین خاطر اگر در خلال کد ما جایی تقسیم بر صفر رخ دهد، خطای تقسیم بر صفر نمایش داده می‌شود. دقت کنید که لزومی ندارد مستقیماً و آگاهانه در خطی از کد تقسیم بر صفر را نوشته باشیم. ممکن است در یک حلقه، شما بر یک متغیر اعداد را تقسیم کنید و آن متغیر تغییر کند و در زمانی، صفر شود.

- **خطای نیافتن فایل (FileNotFoundError)**

اگر در برنامه خود بخواهیم فایل دیگری را بخوانیم و از آن استفاده کنیم اما آدرس را نادرست وارد کنیم و برنامه نتواند آن فایل را پیدا کند، خطای نیافتن فایل نمایش داده می‌شود.

## مدیریت خطا
اولین کاری که در مدیریت خطا قصد داریم انجام دهیم این است که اگر در برنامه خطایی پیش آمد، ما مشخص کنیم که چه اتفاقی بیفتد و لزوماً برنامه متوقف نشود. برای این کار به سادگی می‌توان از قالب زیر استفاده کرد:
```python
try:
    # part of code that may have error
except:
    #what should be done with error
```
مثلاً در قطعه کد زیر، خطای تقسیم صفر را با پیغام دیگری مدیریت می‌کنیم:
```python
try:
    print(1/0)
except:
    print("Why do you divide the number by zero?")
```
البته روشن است که کد بالا ساختگی است و هیچگاه قرار نیست در جایی صراحتاً خطا انجام دهیم.

**نکته.** در مورد قالب بالا باید توجه کنید که می‌شود این قالب را روی کل برنامه گذاشت و این امکان هم وجود دارد که فقط در یک بخش خاص از کد که می‌دانیم خطاخیز است، از این قالب استفاده کنیم.

**نکته ۲.** در قسمت `except` می‌توانیم به طور خاص یک خطای مشخص را مدیریت کنیم. مثلاً:
```python
try:
    print(1/0)
except ZeroDivisionError:
    print("Why do you divide the number by zero?")
```
در این حالت برنامه ما به خطاهای دیگر، کاری ندارد.

نکته ۳. اگر بخواهید از متن خود خطا هم در قسمت `except` استفاده کنید، به شکل زیر این کار ممکن است:

```python
try:
    print(1/0)
except ZeroDivisionError as e:
    print("Why do you divide the number by zero?")
    print(f"The Error is this : {e}")
```

## ایجاد خطا
گاهی ممکن است لازم باشد برنامه‌ای که می‌نویسم برای کاربر خطایی ایجاد کند که لزوماً برنامه‌نویسی نیست بلکه به منطق برنامه برمی‌گردد. مثلاً فرض کنید برنامه‌ای نوشته شده که اول بودن یا نبودن را تشخیص می‌دهد و ورودی این برنامه باید طبیعی باشد اما ما با `int` ورودی می‌گیریم و راه برای اعداد منفی هم باز است اما می‌خواهیم اگر کاربر عدد منفی وارد کرد، برنامه خطا نمایش دهد. برای این کار می‌توانیم به شکل زیر از دستور `raise` استفاده کنیم.
```python
try:
    n = int(input())
    if n<=0:
        raise ValueError
except:
    print('Negative number is not allowed.')
```
اما برای مثال مذکور، شاید راه‌حل بالا هم مناسب نباشد؛ چون اگر کاربر `1.2` هم وارد کند، `ValueError` رخ می‌دهد و با اجرای برنامه فوق، خطای عدد منفی برای این حالت هم نمایش داده می‌شود که درست نیست. یک راه دیگر این است که با استفاده از `Exception` خطای دلخواه خود را ایجاد کنیم.
```python
n = int(input())
if n<=0:
    raise Exception('Negative numbers are not allowed.')
```
